### ISSUE TITLE
Extracting from HTML

### ISSUE THREAD

**Issue by XOlegator** [smhg/gettext-handlebars#7]
I extract translatable strings from my HTML template strings (I make PhoneGap application) by your tool. But I need rename my index.html to index.hbs each time. Could you expand the scope of your tool for html files? In the parser, no changes are needed, just add the html file. Now everything works fine with these lines:
<span class="tabbar-label app-text">{{_ "Settings"}}</span>

**Comment by smhg** [comment]
Language-autodetection can only work for specific extensions (e.g. `.hbs`). Since we parse other types of template languages, we can't bind `.html` to Handlebars.

But you can specify the language of your source files as an argument like so:
```bash
$ xgettext-template -L Handlebars
```
Or if you use Poedit something like:
`xgettext-template --force-po -o %o %C %K %F -L Handlebars`

**Comment by XOlegator** [comment]
It's work! Thanks!
